//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.28010.0
// 
namespace UWPWithWCF.LocalServiceWrapper {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceControllerStatus", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceProcess")]
    public enum ServiceControllerStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContinuePending = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paused = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PausePending = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartPending = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stopped = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StopPending = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalServiceWrapper.ILocalService")]
    public interface ILocalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalService/StartService", ReplyAction="http://tempuri.org/ILocalService/StartServiceResponse")]
        System.Threading.Tasks.Task<UWPWithWCF.LocalServiceWrapper.ServiceControllerStatus> StartServiceAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocalServiceChannel : UWPWithWCF.LocalServiceWrapper.ILocalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalServiceClient : System.ServiceModel.ClientBase<UWPWithWCF.LocalServiceWrapper.ILocalService>, UWPWithWCF.LocalServiceWrapper.ILocalService {
        
        public LocalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<UWPWithWCF.LocalServiceWrapper.ServiceControllerStatus> StartServiceAsync(string name) {
            return base.Channel.StartServiceAsync(name);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
